name: party-mode-audit
description: "Run a structured multi-agent style risk audit on a story before development and append actionable follow-ups."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/party-mode-audit"
instructions: "{installed_path}/instructions.xml"
template: false

variables:
  story_path: "" # Optional explicit story path
  epic_num: "3"
  story_dir: "{implementation_artifacts}"

input_file_patterns:
  epics:
    description: "Epics and stories context"
    whole: "{planning_artifacts}/*epic*.md"
    sharded: "{planning_artifacts}/*epic*/*.md"
    load_strategy: "SELECTIVE_LOAD"
  architecture:
    description: "Architecture guardrails"
    whole: "{planning_artifacts}/*architecture*.md"
    sharded: "{planning_artifacts}/*architecture*/*.md"
    load_strategy: "FULL_LOAD"
  ux_design:
    description: "UX constraints"
    whole: "{planning_artifacts}/*ux*.md"
    sharded: "{planning_artifacts}/*ux*/*.md"
    load_strategy: "FULL_LOAD"

project_context: "**/project-context.md"

standalone: true
